# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

In [13]:
# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 

In [97]:
a = [5, 10, 15, 20]
for i in a:
    print(i)

5
10
15
20


In [98]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [99]:
b = [i**2 for i in a]
print(b)

[25, 100, 225, 400]


In [100]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10.

In [101]:
c = [i**2 if i != 10 else i for i in a]
print(c)


[25, 10, 225, 400]


In [102]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 

In [140]:
import numpy as np 

In [150]:
import random

data = np.random.rand(3,3)

In [151]:
data

array([[0.80587658, 0.03833931, 0.64971749],
       [0.37267483, 0.24254348, 0.20093617],
       [0.49349531, 0.14123701, 0.88039096]])

In [105]:
#(ii)	Write the command to slice the column 1? 

In [152]:

column1 = [row[1] for row in data]
print(column1)

[0.03833930639909522, 0.24254348394387992, 0.14123701296841296]


In [107]:
#(iii)	Write the s of first and third elements in column 1?

In [153]:


first_element = data[0][1]
third_element = data[2][1]

print(first_element, third_element)

0.03833930639909522 0.14123701296841296


In [109]:
#(iv)	 Write the command of returns an 8 x 4 array

In [154]:
import numpy as np

array_8x4 = np.zeros((8, 4))
print(array_8x4)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [155]:
import pandas as pd 

In [112]:
# #Q3. Create a Series that looks like this below:
# Flour     4 cups
# Milk       1 cup
# Eggs     2 large
# Spam       1 can
# Name: Dinner, dtype: object

In [113]:

data = {'Flour': '4 cups',
        'Milk': '1 cup',
        'Eggs': '2 large',
        'Spam': '1 can'}

dinner_series = pd.Series(data, name='Dinner')
print(dinner_series)


Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object


In [114]:
# Q  4 Create the Data frame  as th output[27]

In [115]:

data = {'Apples': [35, 41],
        'Bananas': [21, 34]}

df = pd.DataFrame(data, index=['2017Sales', '2018Sales'])

In [116]:
df

Apples  Bananas
2017Sales      35       21
2018Sales      41       34

In [117]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [118]:
data = {
    'Age': [23.0, 39.0, 45.0, np.nan],
    'Gender': ['M', 'F', 'F', 'M'],
    'Income': [24200.0, np.nan, 45390.0, np.nan],
    'Religion': ['Muslim', 'Christian', np.nan, 'Muslim']
}

df = pd.DataFrame(data)
df


Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  Christian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [119]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  Christian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [120]:
#Q4(i)	Compute the appropriate missing value in income attribute?

In [121]:

# Impute missing values with mean
df['Income'].fillna(df['Income'].mean(), inplace=True)


print(df)

    Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F  34795.0  Christian
2  45.0      F  45390.0        NaN
3   NaN      M  34795.0     Muslim


In [122]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [123]:

df['Religion'].fillna('Unknown', inplace=True)

In [124]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F  34795.0  Christian
2  45.0      F  45390.0    Unknown
3   NaN      M  34795.0     Muslim

In [125]:
#(iii)	Drop the columns where any of the elements is nan

In [126]:
df = df.dropna(axis=1)

df

Gender   Income   Religion
0      M  24200.0     Muslim
1      F  34795.0  Christian
2      F  45390.0    Unknown
3      M  34795.0     Muslim

In [127]:
#(iv)	Keep only the rows with at least 2 non-na values

In [128]:
df = df.dropna(thresh=2)
df

Gender   Income   Religion
0      M  24200.0     Muslim
1      F  34795.0  Christian
2      F  45390.0    Unknown
3      M  34795.0     Muslim